//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class JRodriguezExamenPracticoMichelinEntities : DbContext
    {
        public JRodriguezExamenPracticoMichelinEntities()
            : base("name=JRodriguezExamenPracticoMichelinEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Localizacione> Localizaciones { get; set; }
    
        public virtual ObjectResult<LocalizacionesGetAll_Result> LocalizacionesGetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LocalizacionesGetAll_Result>("LocalizacionesGetAll");
        }
    }
}
